// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0bkbsJnNk2w5yFjXm4bofZsaYVJUgmA',
    appId: '1:291561999324:web:f09fad6b997fcb60921d19',
    messagingSenderId: '291561999324',
    projectId: 'ki-sun-lounge-app',
    authDomain: 'ki-sun-lounge-app.firebaseapp.com',
    storageBucket: 'ki-sun-lounge-app.firebasestorage.app',
    measurementId: 'G-34L7ZQY75Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrsURQ3JeiPJ_cbxVxFcNSiA3EhCJwg-A',
    appId: '1:291561999324:android:ad219669a9e15e43921d19',
    messagingSenderId: '291561999324',
    projectId: 'ki-sun-lounge-app',
    storageBucket: 'ki-sun-lounge-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-mbKq4616VsaZOjJj0wzKIDf7VKNFgbo',
    appId: '1:291561999324:ios:14d60382b04efd40921d19',
    messagingSenderId: '291561999324',
    projectId: 'ki-sun-lounge-app',
    storageBucket: 'ki-sun-lounge-app.firebasestorage.app',
    iosBundleId: 'com.example.kiSun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-mbKq4616VsaZOjJj0wzKIDf7VKNFgbo',
    appId: '1:291561999324:ios:14d60382b04efd40921d19',
    messagingSenderId: '291561999324',
    projectId: 'ki-sun-lounge-app',
    storageBucket: 'ki-sun-lounge-app.firebasestorage.app',
    iosBundleId: 'com.example.kiSun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0bkbsJnNk2w5yFjXm4bofZsaYVJUgmA',
    appId: '1:291561999324:web:85fe290295bb8ab2921d19',
    messagingSenderId: '291561999324',
    projectId: 'ki-sun-lounge-app',
    authDomain: 'ki-sun-lounge-app.firebaseapp.com',
    storageBucket: 'ki-sun-lounge-app.firebasestorage.app',
    measurementId: 'G-1M08XBVVRX',
  );
}
